version: '3'

services:
     prod:
        container_name: nest-auth
        build: ./
        environment:
            POSTGRES_USER: gdcodurbzfmmgs
            POSTGRES_PASSWORD: ba5253ee0f6d3ab8fcb927d12a922e48049db2db599ae8afd4218a4059dfa42b
            POSTGRES_DB: d7f7js7avvsfdp
            POSTGRES_HOST: ec2-3-248-87-6.eu-west-1.compute.amazonaws.com
        ports:
            - 3050:3000
        restart: unless-stopped
    # dev:
    #     container_name: nestjs_api_dev
    #     image: nestjs-api-dev:1.0.0
    #     build:
    #         context: .
    #         target: development
    #         dockerfile: ./Dockerfile
    #     command: npm run start:debug
    #     ports:
    #         - 3000:3000
    #         - 9229:9229
    #     networks:
    #         - nesjs-network
    #     volumes:
    #         - .:/usr/src/app
    #         - /usr/src/app/node_modules
    #     restart: unless-stopped
 

